version: '3.8'

services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5050:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ldap:
    image: bitnami/openldap:latest
    env_file:
      - .env
    ports:
      - "1389:1389"

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5051:5051"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./scheduler:/app/scheduler
