[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scheduler"
version = "0.1.0"
description = "Your package description"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
dependencies = [
    "blinker",
    "cachelib",
    "click",
    "erd",
    "Flask",
    "Flask-Mail",
    "flask-migrate>=4.0.7",
    "Flask-Session",
    "Flask-SQLAlchemy",
    "Flask-WTF",
    "ipython>=8.30.0",
    "itsdangerous",
    "Jinja2",
    "MarkupSafe",
    "pdbpp>=0.10.3",
    "psycopg2",
    "python-dotenv",
    "SQLAlchemy",
    "sync>=1.0.0",
    "Werkzeug",
    # Add other dependencies as needed
    "WTForms",
]

[project.optional-dependencies]
dev = [
    "mypy>=0.910",
    "black>=21.5b0"
    # Add other dev dependencies if needed
]

[project.urls]
Homepage = "https://your.project.homepage"

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*"]
