begin;

create table supportkind (
	supportkind int generated by default as identity primary key,
	label text not null,
	unique(label)
);

comment on table supportkind is 'Kind of support request';
comment on column supportkind.supportkind is 'primary key';
comment on column supportkind.label is 'human readable label';

insert into supportkind(label) values ('medical coverage'), ('training'), ('technologist');

create table support (
	schedid int,
	supportkind int,
	filed_by varchar(20) not null,
	fulfilled_by varchar(20),
	approved boolean, -- null = not yet decided
	note text not null default '', -- only for technologist, to record scan vs. cover
	chg_by varchar(20) not null,
	chg_at timestamp with time zone not null default current_timestamp,
	constraint support_schedid_fkey foreign key (schedid) references tblsched(schedid) on delete restrict,
	constraint support_supportkind_fkey foreign key (supportkind) references supportkind(supportkind) on delete restrict,
	constraint support_filed_by_fkey foreign key (filed_by) references tlkpresearcher(researchercode) on update cascade on delete restrict,
	constraint support_fulfilled_by_fkey foreign key (fulfilled_by) references tlkpresearcher(researchercode) on update cascade on delete restrict,
	constraint support_chg_by_fkey foreign key (chg_by) references tlkpresearcher(researchercode) on update cascade on delete restrict,
	primary key(schedid, supportkind)
);

comment on table support is 'support requests for slot';
comment on column support.schedid is 'first half of primary key';
comment on column support.supportkind is 'second half of primary key';
comment on column support.filed_by is 'user who filed this request';
comment on column support.fulfilled_by is 'user who will fulfill this request';
comment on column support.approved is 'whether this request has been approved (null = not yet decided)';
comment on column support.note is 'used by technologist requests to disambiguate cover/scan requests';
comment on column support.chg_by is 'user who last modified this request';
comment on column support.chg_at is 'timestamp of last modification';

create table supportlog (
	logid bigint generated by default as identity primary key,
	schedid int,
	supportkind int,
	filed_by varchar(20),
	fulfilled_by varchar(20),
	approved boolean,
	note text not null,
	filed_by_old varchar(20),
	fulfilled_by_old varchar(20),
	approved_old boolean,
	note_old text not null default '',
	chg_by varchar(20) not null,
	chg_at timestamp with time zone not null,
	constraint supportlog_fkey foreign key (schedid, supportkind) references support(schedid, supportkind) on delete cascade
);

comment on table supportlog is 'Logged changes from support';

create function log_support_impl() returns trigger as $$
	begin
		if(TG_OP = 'UPDATE') then
			insert into supportlog (
				schedid, supportkind,
				filed_by, fulfilled_by, approved, note,
				filed_by_old, fulfilled_by_old, approved_old, note_old,
				chg_by, chg_at
			) values (
				NEW.schedid, NEW.supportkind,
				NEW.filed_by, NEW.fulfilled_by, NEW.approved, NEW.note,
				OLD.filed_by, OLD.fulfilled_by, OLD.approved, old.note,
				NEW.chg_by, NEW.chg_at
			);
		elseif(TG_OP = 'INSERT') then
			insert into supportlog (
				schedid, supportkind,
				filed_by, fulfilled_by, approved, note,
				chg_by, chg_at
			) values (
				NEW.schedid, NEW.supportkind,
				NEW.filed_by, NEW.fulfilled_by, NEW.approved, NEW.note,
				NEW.chg_by, NEW.chg_at
			);
		end if;
		return NEW;
	end;
$$
language plpgsql;

create trigger log_support_changes after insert or update on support for each row execute procedure log_support_impl();

commit;
